import Head from "next/head";
import { useEffect, useState } from "react";
import { getAll } from "../services/directus/utils";
import styles from "../styles/Months.module.css";
import { useUxContext } from "../contexts/uxContext";
import Month from "../components/ux/Month/Month";

const Months = ({ fruits, vegetables, months }) => {
  const [fruitsMonths, setFruitsMonths] = useState([]);
  const [vegetablesMonths, setVegetablesMonths] = useState([]);

  const { selectedType } = useUxContext();

  useEffect(() => {
    let nouv = [];
    for (let i = 0; i < months.length; i++) {
      let mois = [{ name: months[i].name, num: months[i].number }];
      for (let j = 0; j < fruits.length; j++) {
        if (fruits[j].month.includes(months[i].number.toString())) {
          mois.push(fruits[j]);
        }
      }
      nouv.push(mois);
    }

    setFruitsMonths(nouv);
  }, [fruits, months]);

  useEffect(() => {
    let nouv = [];
    for (let i = 0; i < months.length; i++) {
      let mois = [{ name: months[i].name, num: months[i].number }];
      for (let j = 0; j < vegetables.length; j++) {
        if (vegetables[j].month.includes(months[i].number.toString())) {
          mois.push(vegetables[j]);
        }
      }
      nouv.push(mois);
    }

    setVegetablesMonths(nouv);
  }, [vegetables, months]);

  return (
    <>
      <Head>
        <title>Fruits et légumes de saison | Season</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        {selectedType === "fruits" && fruitsMonths && fruitsMonths.map((m) => <Month month={m} key={m[0].num} />)}
        {selectedType === "legumes" && vegetablesMonths && vegetablesMonths.map((m) => <Month month={m} key={m[0].num} />)}
      </div>
    </>
  );
};

export async function getStaticProps() {
  const fruits = await getAll("fruit");
  const vegetables = await getAll("vegetable");
  const months = await getAll("months");

  return {
    props: {
      fruits: fruits,
      vegetables: vegetables,
      months: months,
    },
  };
}

export default Months;
